### ISSUE TITLE
fix:lint fails on Windows

### ISSUE THREAD

**Issue by Bellisario** [coderaiser/goldstein#4]
While running `npm run fix:lint` on Windows it fails and logs:
`Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'`

Same problem testing [with GitHub actions](https://github.com/Bellisario/goldstein-test/runs/7028939668?check_suite_focus=true#step:5:11) on `windows-latest`.

**Comment by Bellisario** [comment]
Seems it's a problem with madrun because it fail [also running coverage](https://github.com/Bellisario/goldstein-test/runs/7029162438?check_suite_focus=true#step:11:11) (after skipping lint).

**Comment by coderaiser** [comment]
I don't have `windows` unfortunately, could you please help me to find the source of a problem?

**Comment by coderaiser** [comment]
Looks like [`madrun`](https://github.com/coderaiser/madrun) cannot start.
It has [such code](https://github.com/coderaiser/madrun/blob/v9.0.4/bin/madrun.mjs#L163-L164):

```js
// always convert path to url on windows
const esm = await import(pathToFileURL(path));
```

Especially for windows.

**Comment by Bellisario** [comment]
`pathToFileURL` import seems to work correctly (I tried with Node.js REPL):
```
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> const {pathToFileURL} = require('url');
undefined
> const esm = await import(pathToFileURL('C:/Users/Giorgio/GitHub/goldstein-test
1/packages/goldstein/index.js'))
undefined
>
> esm
[Module: null prototype] { compile: [Function: compile] }
>
```

The bad things is that there aren't additional (helpful) logs:
```
C:\Users\Giorgio\GitHub\goldstein>npm run fix:lint

> goldstein@2.0.0 fix:lint C:\Users\Giorgio\GitHub\goldstein
> madrun fix:lint

Only URLs with a scheme in: file, data are supported by the default ESM loader.
On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! goldstein@2.0.0 fix:lint: `madrun fix:lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the goldstein@2.0.0 fix:lint script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Giorgio\AppData\Roaming\npm-cache\_logs\2022-06-23T18_21_0
0_896Z-debug.log

C:\Users\Giorgio\GitHub\goldstein>
```
Here is also the NPM log file content:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'fix:lint'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v16.15.0
4 verbose run-script [ 'prefix:lint', 'fix:lint', 'postfix:lint' ]
5 info lifecycle goldstein@2.0.0~prefix:lint: goldstein@2.0.0
6 info lifecycle goldstein@2.0.0~fix:lint: goldstein@2.0.0
7 verbose lifecycle goldstein@2.0.0~fix:lint: unsafe-perm in lifecycle true
8 verbose lifecycle goldstein@2.0.0~fix:lint: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Giorgio\GitHub\goldstein\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\dotnet\;C:\Program Files\Go\bin;C:\TDM-GCC-64\bin;C:\Users\Giorgio\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\Giorgio\AppData\Local\Programs\Python\Python38\;C:\Users\Giorgio\Downloads\hyper-Setup-3.0.2\hyper-3.0.2-full\lib\net45\resources\bin;\bin-win;C:\Users\Giorgio\AppData\Roaming\npm;C:\Program Files\deno;C:\MinGW\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Giorgio\go\bin
9 verbose lifecycle goldstein@2.0.0~fix:lint: CWD: C:\Users\Giorgio\GitHub\goldstein
10 silly lifecycle goldstein@2.0.0~fix:lint: Args: [ '/d /s /c', 'madrun fix:lint' ]
11 silly lifecycle goldstein@2.0.0~fix:lint: Returned: code: 1  signal: null
12 info lifecycle goldstein@2.0.0~fix:lint: Failed to exec fix:lint script
13 verbose stack Error: goldstein@2.0.0 fix:lint: `madrun fix:lint`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:527:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:527:28)
13 verbose stack     at maybeClose (node:internal/child_process:1092:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
14 verbose pkgid goldstein@2.0.0
15 verbose cwd C:\Users\Giorgio\GitHub\goldstein
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "fix:lint"
18 verbose node v16.15.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error goldstein@2.0.0 fix:lint: `madrun fix:lint`
22 error Exit status 1
23 error Failed at the goldstein@2.0.0 fix:lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I don't understand where can be the problem, seems shouldn't be any error...

**Comment by coderaiser** [comment]
Looks, like [I fixed](https://github.com/coderaiser/madrun/commit/fcc7d291094b438167b7f019b550a5aac2ec019d) 🎉.

Also added `Windows CI` to [madrun](https://github.com/coderaiser/madrun/actions/workflows/windows.yml), thanks for idea!
Also added the same for [goldstein](https://github.com/coderaiser/goldstein/actions/workflows/windows.yml), so this want happen again :).

Actually, `windows` is really pain in ass, what do you think about using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)? Linux and Mac Os works in similar way, and only windows has lots of surprises...

**Comment by Bellisario** [comment]
@coderaiser, I also hate Windows, but currently I can't change to macOS or Linux...
The bad thing is that I also have an about old PC that runs Windows 7, minimum requirements for WSL is Windows 10... :cry:

I can confirm now madrun works! I'll close this issue.
Instead on the pull request (#3) I am facing another strange error, I'll see if I can solve, I think this is another strange Windows problem :face_exhaling:

**Comment by Bellisario** [comment]
Sorry, I reopened this issue...

Seems Madrun now works with "lint" script (I tested initially tested only this) but not with "fix:lint".
I think this is a problem of the ":", maybe (I only suppose) it is interpreted as a URL "http:", "https:" or something similar (a disk, ex. "C:")???

**Comment by coderaiser** [comment]
You can try `gitpod`, this is only IDE which works from the browser: https://gitpod.io/#https://github.com/coderaiser/goldstein

**Comment by Bellisario** [comment]
Thanks for the suggestion, now all works correctly using Gitpod!
One little thing, for who wants to contribute it's better to know they need not to use Windows (maybe with an alert on README.md) or they can have a lot of issues.

P.S.: I'll close also the #3 pull request because all seems to work properly now...
